nodeLinker: node-modules
yarnPath: .yarn/releases/yarn-3.4.1.cjs
enableGlobalCache: true

packageExtensions:
  "@craco/craco@*":
    peerDependencies:
      "@types/node": "*"
      typescript: "*"
    dependencies:
      postcss: "*"
  react-scripts@*:
    dependencies:
      "@babel/plugin-syntax-flow": "*"
      "@babel/plugin-transform-react-jsx": "*"
  eslint-config-react-app@*:
    peerDependencies:
      "@babel/plugin-syntax-flow": "*"
      "@babel/plugin-transform-react-jsx": "*"